#!/usr/bin/env python3
"""Deterministic local governance utilities for Violence_Checker.

Provenance: adapted from read-only reference tooling in
`/Users/joellipton/Desktop/foxcommand-runtime/tools/repo_governance.py` and
`/Users/joellipton/Desktop/foxcommand-runtime/tools/validate_sitrec.py`.

This local version intentionally omits FoxCommand manifest lifecycle, runtime
boundary, closeout, deployment, and documentation synchronization behavior.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


DEFAULT_REPOSITORY_TREE_PATH = Path("docs/generated/repository_tree.txt")
DEFAULT_KNOWLEDGE_GRAPH_PATH = Path("docs/generated/repository_knowledge_graph.md")
HEARTBEAT_PATH = Path("telemetry/executor_heartbeat.jsonl")

EXCLUDED_DIRS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".streamlit",
    ".venv",
    "__pycache__",
    "build",
    "coverage",
    "dist",
    "env",
    "node_modules",
    "venv",
}

EXCLUDED_FILES = {
    ".DS_Store",
    ".env",
    "Thumbs.db",
}

SECRET_NAME_PATTERNS = (
    re.compile(r"(^|/)\.env($|\.)"),
    re.compile(r"(^|/)secrets\.toml$"),
)

REQUIRED_SITREC_SECTIONS = [
    "A. SYSTEM IDENTITY",
    "B. CURRENT STATE",
    "C. CORE INVARIANTS",
    "D. SYSTEM MODEL",
    "E. AUTHORITY MODEL",
    "F. DATA / CONTRACT MODEL",
    "G. SYSTEM BOUNDARIES",
    "H. CURRENT CAPABILITIES",
    "I. KNOWN LIMITATIONS",
    "J. INTERACTION MODEL",
    "K. GUARANTEES",
    "L. NON-GUARANTEES",
    "M. GROUNDING ANCHORS",
    "N. SOURCE OF TRUTH RULE",
    "O. REHYDRATION INSTRUCTIONS",
]

PROVIDER_FACING_MODULES = {
    "src/config.py",
    "src/semantic_extractor.py",
    "src/semantic_prompt.py",
    "src/salesforce_preview.py",
}

APPLICATION_COMPONENTS = {
    "app.py",
    "src/app_logic.py",
    "src/comparison.py",
    "src/fixtures.py",
    "src/models.py",
    "src/regex_baseline.py",
}

ENTRY_POINT_PATTERNS = (
    "app.py",
    "scripts/*.py",
    "tools/repo_governance/__main__.py",
)


@dataclass(frozen=True)
class Finding:
    path: str
    message: str


def resolve_repo_root(path: Path) -> Path:
    candidate = path.expanduser().resolve()
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        cwd=candidate,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise ValueError(f"not a Git repository: {candidate}")
    return Path(result.stdout.strip()).resolve()


def ensure_inside_root(root: Path, path: Path) -> Path:
    target = path if path.is_absolute() else root / path
    target = target.resolve()
    try:
        target.relative_to(root)
    except ValueError as error:
        raise ValueError(f"output path escapes repository root: {target}") from error
    return target


def is_excluded(relative: Path) -> bool:
    parts = relative.parts
    if relative.name in EXCLUDED_FILES:
        return True
    if any(part in EXCLUDED_DIRS for part in parts):
        return True
    posix = relative.as_posix()
    return any(pattern.search(posix) for pattern in SECRET_NAME_PATTERNS)


def repository_entries(root: Path) -> list[str]:
    entries: list[str] = []
    for path in root.rglob("*"):
        relative = path.relative_to(root)
        if is_excluded(relative):
            if path.is_dir():
                continue
            continue
        suffix = "/" if path.is_dir() else ""
        entries.append(relative.as_posix() + suffix)
    return sorted(entries)


def repository_files(root: Path) -> list[str]:
    return [entry for entry in repository_entries(root) if not entry.endswith("/")]


def write_repository_tree(root: Path, output: Path = DEFAULT_REPOSITORY_TREE_PATH) -> dict[str, object]:
    root = resolve_repo_root(root)
    target = ensure_inside_root(root, output)
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Violence_Checker Repository Tree",
        "",
        "Generated by `python3 -m tools.repo_governance repo-tree`.",
        "Entries are sorted, repository-relative, and exclude ignored local configuration, caches, transient environments, and `.git` internals.",
        "",
    ]
    lines.extend(repository_entries(root))
    target.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return {"path": target.relative_to(root).as_posix(), "entries": len(repository_entries(root))}


def parse_python_file(path: Path) -> tuple[list[str], list[str], list[str]]:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except SyntaxError:
        return [], [], []
    imports: set[str] = set()
    classes: set[str] = set()
    functions: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            module = "." * node.level + (node.module or "")
            imports.add(module)
        elif isinstance(node, ast.ClassDef):
            classes.add(node.name)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            functions.add(node.name)
    return sorted(imports), sorted(classes), sorted(functions)


def markdown_table(headers: list[str], rows: list[list[str]]) -> list[str]:
    output = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _header in headers) + " |",
    ]
    output.extend("| " + " | ".join(row) + " |" for row in rows)
    return output


def active_sitrec_paths(root: Path) -> list[str]:
    docs = root / "docs"
    if not docs.exists():
        return []
    return sorted(
        path.relative_to(root).as_posix()
        for path in docs.glob("*.md")
        if "sitrec" in path.name.lower()
    )


def build_knowledge_graph(root: Path) -> str:
    files = repository_files(root)
    python_files = [value for value in files if value.endswith(".py")]
    docs = [value for value in files if value.startswith("docs/") and value.endswith(".md")]
    tests = [value for value in files if value.startswith("tests/test_") and value.endswith(".py")]

    module_rows: list[list[str]] = []
    import_rows: list[list[str]] = []
    contract_rows: list[list[str]] = []
    for relative in python_files:
        imports, classes, functions = parse_python_file(root / relative)
        role = "provider-facing" if relative in PROVIDER_FACING_MODULES else "deterministic"
        if relative in APPLICATION_COMPONENTS:
            role = "deterministic application component"
        if relative.startswith("tests/"):
            role = "deterministic test"
        if relative.startswith("tools/repo_governance/"):
            role = "deterministic governance tooling"
        module_rows.append([f"`{relative}`", role, ", ".join(f"`{name}`" for name in classes) or "none", str(len(functions))])
        import_rows.append([f"`{relative}`", ", ".join(f"`{name}`" for name in imports) or "none"])
        for class_name in classes:
            if relative.startswith("src/") or relative.startswith("tools/repo_governance/"):
                contract_rows.append([f"`{class_name}`", f"`{relative}`"])

    test_rows: list[list[str]] = []
    for test_path in tests:
        target = test_path.removeprefix("tests/test_").removesuffix(".py")
        candidates = [
            f"src/{target}.py",
            f"{target}.py",
        ]
        covered = next((candidate for candidate in candidates if candidate in files), "unresolved")
        test_rows.append([f"`{test_path}`", f"`{covered}`" if covered != "unresolved" else "unresolved"])

    entry_rows: list[list[str]] = []
    for pattern in ENTRY_POINT_PATTERNS:
        matches = sorted(path.relative_to(root).as_posix() for path in root.glob(pattern) if path.is_file())
        for match in matches:
            entry_rows.append([f"`{match}`", "local executable entry point"])

    boundary_rows = [
        ["Deterministic application components", ", ".join(f"`{path}`" for path in sorted(APPLICATION_COMPONENTS) if path in files)],
        ["Provider-facing components", ", ".join(f"`{path}`" for path in sorted(PROVIDER_FACING_MODULES) if path in files)],
        ["Current pipeline boundary", "`src/app_logic.py` orchestrates regex, semantic extraction, comparison, and Salesforce preview gating."],
        ["Unresolved relationships", "No repository-local static evidence connects this project to FoxCommand runtime application modules."],
    ]

    grouped_docs: dict[str, list[str]] = defaultdict(list)
    for doc in docs:
        if "SITREC" in Path(doc).name:
            grouped_docs["SITREC"].append(doc)
        elif doc.startswith("docs/generated/"):
            grouped_docs["generated"].append(doc)
        else:
            grouped_docs["documentation"].append(doc)
    doc_rows = [[key, ", ".join(f"`{item}`" for item in values)] for key, values in sorted(grouped_docs.items())]

    lines = [
        "# Violence_Checker Repository Knowledge Graph",
        "",
        "Generated by `python3 -m tools.repo_governance knowledge-graph` from repository content.",
        "",
        "## Scope",
        "",
        "This graph records deterministic repository relationships discoverable from files, imports, tests, documentation names, and governance artifact locations. It does not infer clinical, production, or external integration claims.",
        "",
        "## Entry Points",
        "",
        *markdown_table(["Artifact", "Relationship"], entry_rows),
        "",
        "## Pipeline Boundaries",
        "",
        *markdown_table(["Boundary", "Repository evidence"], boundary_rows),
        "",
        "## Python Modules",
        "",
        *markdown_table(["Module", "Role", "Classes", "Function count"], module_rows),
        "",
        "## Import Relationships",
        "",
        *markdown_table(["Module", "Imports"], import_rows),
        "",
        "## Contracts",
        "",
        *markdown_table(["Contract", "Declared in"], sorted(contract_rows)),
        "",
        "## Tests",
        "",
        *markdown_table(["Test artifact", "Static target"], test_rows),
        "",
        "## Documentation",
        "",
        *markdown_table(["Documentation group", "Artifacts"], doc_rows),
        "",
        "## Governance Artifacts",
        "",
        *markdown_table(
            ["Artifact", "Relationship"],
            [
                ["`tools/repo_governance/`", "Local deterministic governance tooling copied and narrowed from foxcommand-runtime reference tooling."],
                ["`docs/generated/repository_tree.txt`", "Generated deterministic repository tree."],
                ["`docs/generated/repository_knowledge_graph.md`", "Generated deterministic repository knowledge graph."],
                ["`telemetry/executor_heartbeat.jsonl`", "Executor operations telemetry validated as JSONL."],
                [", ".join(f"`{path}`" for path in active_sitrec_paths(root)), "Active top-level SITREC candidates."],
            ],
        ),
        "",
        "## Unresolved Relationships",
        "",
        "- Test-to-module links are marked unresolved when no direct filename convention match exists.",
        "- Runtime relationships outside this repository are unresolved unless represented by repository-local files.",
    ]
    return "\n".join(lines).rstrip() + "\n"


def write_knowledge_graph(root: Path, output: Path = DEFAULT_KNOWLEDGE_GRAPH_PATH) -> dict[str, object]:
    root = resolve_repo_root(root)
    target = ensure_inside_root(root, output)
    target.parent.mkdir(parents=True, exist_ok=True)
    content = build_knowledge_graph(root)
    target.write_text(content, encoding="utf-8")
    return {"path": target.relative_to(root).as_posix(), "bytes": len(content.encode("utf-8"))}


def normalize_heading(line: str) -> str:
    line = re.sub(r"^#{1,6}\s*", "", line.strip())
    line = re.sub(r"\s+", " ", line)
    return line.upper()


def sitrec_section_positions(text: str) -> dict[str, int]:
    positions: dict[str, int] = {}
    for index, line in enumerate(text.splitlines()):
        normalized = normalize_heading(line)
        for section in REQUIRED_SITREC_SECTIONS:
            if normalized == section:
                positions.setdefault(section, index)
    return positions


def section_text(text: str, section: str) -> str:
    lines = text.splitlines()
    positions = sitrec_section_positions(text)
    if section not in positions:
        return ""
    start = positions[section] + 1
    next_indexes = [index for name, index in positions.items() if index > positions[section] and name != section]
    end = min(next_indexes) if next_indexes else len(lines)
    return "\n".join(lines[start:end]).strip()


def validate_sitrec_file(path: Path) -> list[Finding]:
    text = path.read_text(encoding="utf-8")
    positions = sitrec_section_positions(text)
    findings: list[Finding] = []
    for section in REQUIRED_SITREC_SECTIONS:
        if section not in positions:
            findings.append(Finding(path.as_posix(), f"missing required section: {section}"))
    grounding = section_text(text, "M. GROUNDING ANCHORS")
    if not grounding:
        findings.append(Finding(path.as_posix(), "grounding section empty"))
    elif not re.search(r"(`[^`]+`)|(\[[^\]]+\]\s*\n\s*<[^>]+>)", grounding):
        findings.append(Finding(path.as_posix(), "grounding section has no artifact reference"))
    if "repository wins" not in section_text(text, "N. SOURCE OF TRUTH RULE").lower() and "repository state is authoritative" not in section_text(text, "N. SOURCE OF TRUTH RULE").lower():
        findings.append(Finding(path.as_posix(), "source-of-truth section does not declare repository primacy"))
    return findings


def validate_heartbeat_jsonl(path: Path) -> list[Finding]:
    findings: list[Finding] = []
    if not path.exists():
        return [Finding(path.as_posix(), "heartbeat JSONL file is missing")]
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not raw_line.strip():
            findings.append(Finding(path.as_posix(), f"line {line_number} is blank"))
            continue
        try:
            event = json.loads(raw_line)
        except json.JSONDecodeError as error:
            findings.append(Finding(path.as_posix(), f"line {line_number} is not valid JSON: {error.msg}"))
            continue
        if event.get("event_type") != "executor_ops":
            findings.append(Finding(path.as_posix(), f"line {line_number} event_type is not executor_ops"))
        if event.get("actor") != "codex":
            findings.append(Finding(path.as_posix(), f"line {line_number} actor is not codex"))
        payload = event.get("payload")
        if not isinstance(payload, dict):
            findings.append(Finding(path.as_posix(), f"line {line_number} payload is not an object"))
            continue
        operations = payload.get("operations")
        if not isinstance(operations, list) or not operations:
            findings.append(Finding(path.as_posix(), f"line {line_number} operations is not a non-empty list"))
            continue
        for operation_index, operation in enumerate(operations, start=1):
            if not isinstance(operation, dict):
                findings.append(Finding(path.as_posix(), f"line {line_number} operation {operation_index} is not an object"))
                continue
            if operation.get("mode") not in {"planned", "autonomous"}:
                findings.append(Finding(path.as_posix(), f"line {line_number} operation {operation_index} has invalid mode"))
            for key in ("action", "reason"):
                if not isinstance(operation.get(key), str) or not operation[key].strip():
                    findings.append(Finding(path.as_posix(), f"line {line_number} operation {operation_index} missing {key}"))
    return findings


def command_repo_tree(args: argparse.Namespace) -> int:
    summary = write_repository_tree(args.repo_root, args.output)
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


def command_knowledge_graph(args: argparse.Namespace) -> int:
    summary = write_knowledge_graph(args.repo_root, args.output)
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


def command_validate_heartbeat(args: argparse.Namespace) -> int:
    root = resolve_repo_root(args.repo_root)
    path = ensure_inside_root(root, args.path)
    findings = validate_heartbeat_jsonl(path)
    return print_findings("heartbeat JSONL validation", findings)


def command_validate_sitrec(args: argparse.Namespace) -> int:
    root = resolve_repo_root(args.repo_root)
    path = ensure_inside_root(root, args.path)
    findings = validate_sitrec_file(path)
    return print_findings("SITREC validation", findings)


def command_validate_all(args: argparse.Namespace) -> int:
    root = resolve_repo_root(args.repo_root)
    findings: list[Finding] = []
    findings.extend(validate_heartbeat_jsonl(root / HEARTBEAT_PATH))
    for path in active_sitrec_paths(root):
        findings.extend(validate_sitrec_file(root / path))
    for output in (args.tree_output, args.graph_output):
        target = ensure_inside_root(root, output)
        if not target.exists():
            findings.append(Finding(target.relative_to(root).as_posix(), "generated artifact is missing"))
    return print_findings("local governance validation", findings)


def print_findings(label: str, findings: list[Finding]) -> int:
    if findings:
        print(f"{label} findings:")
        for finding in findings:
            print(f"- {finding.path}: {finding.message}")
        return 1
    print(f"{label} passed")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Violence_Checker deterministic local governance tooling.")
    parser.add_argument("--repo-root", type=Path, default=Path.cwd(), help="explicit repository root or path inside it")
    subparsers = parser.add_subparsers(dest="command", required=True)

    repo_tree = subparsers.add_parser("repo-tree", help="generate deterministic repository tree")
    repo_tree.add_argument("--output", type=Path, default=DEFAULT_REPOSITORY_TREE_PATH)
    repo_tree.set_defaults(func=command_repo_tree)

    graph = subparsers.add_parser("knowledge-graph", help="generate deterministic repository knowledge graph")
    graph.add_argument("--output", type=Path, default=DEFAULT_KNOWLEDGE_GRAPH_PATH)
    graph.set_defaults(func=command_knowledge_graph)

    heartbeat = subparsers.add_parser("validate-heartbeat", help="validate executor heartbeat JSONL")
    heartbeat.add_argument("--path", type=Path, default=HEARTBEAT_PATH)
    heartbeat.set_defaults(func=command_validate_heartbeat)

    sitrec = subparsers.add_parser("validate-sitrec", help="validate one SITREC artifact")
    sitrec.add_argument("--path", type=Path, required=True)
    sitrec.set_defaults(func=command_validate_sitrec)

    validate_all = subparsers.add_parser("validate-all", help="run local deterministic governance validators")
    validate_all.add_argument("--tree-output", type=Path, default=DEFAULT_REPOSITORY_TREE_PATH)
    validate_all.add_argument("--graph-output", type=Path, default=DEFAULT_KNOWLEDGE_GRAPH_PATH)
    validate_all.set_defaults(func=command_validate_all)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except ValueError as error:
        print(f"repo_governance error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
